# 端口号
server:
  port: 7900
# 数据库相关配置
spring:
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  # 数据源
  datasource:

    #driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/uff_testdb?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: p@ssw0rd!

# 日志
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: DEBUG
    org.hibernate.type.descriptor.sql.BasicExtractor: DEBUG
    com.springms: DEBUG